pipeline {

agent any

options {
    timeout (time:5,unit: 'MINUTES')
    buildDiscarder(logRotator(numToKeepStr: '5'))
    disableConcurrentBuilds()
}

parameters {
    choice choices: ['deploy', 'rollout'], description: '选择构建模式', name: 'MODE'
    choice choices: ['online', 'offline'], description: '线上/线下', name: 'TYPE'
    choice choices: ['dfsjfm-system', 'hmf-system', 'ktingfm-system', 'frontend'], description: '选择部署环境 ', name: 'DEPLOY_NS'
    choice choices: ['NewApp', 'trunk','developer'], description: '选择代码分支', name: 'CODE_BRANCH'
}

environment {
    //参数化构建相关环境变量
    MODE = "${params.MODE}"
    DEPLOY_NS = "${params.DEPLOY_NS}"
    CODE_BRANCH = "${params.CODE_BRANCH}"
    TYPE = "${params.TYPE}"

    //获取代码相关环境变量
    CODE_NAME = "API"
    GITLAB_CRE = "gitlab.dfsjfm.com"
    GITLAB_URL = "http://gitlab.dfsjfm.com/alex/HUAWEI_MUSIC_${CODE_NAME}_V1.git"

    //生成Docker Image推送至Docker Registry相关环境变量
    TIME_STAMP = sh(script: "date '+%Y%m%d%H%M%S'",returnStdout: true).trim()
    DOCKER_SITE = "jenkins_dockersite"
    DOCKER_REGISTRY = "harbor.dfsjfm.com"
    DOCKER_REGISTRY_CRE = "harbor.dfsjfm.com"
    DOCKER_IMAGE_TAG = "${TYPE}${TIME_STAMP}_${BUILD_NUMBER}"
    DOCKER_IMAGE_FULL_NAME = "${DOCKER_REGISTRY}/${DEPLOY_NS}/${JOB_NAME}:${DOCKER_IMAGE_TAG}"

    //发布至Kubernetes相关环境变量
    KUBE_CRE = "jenkins-workflow"
    KUBE_APISERVER = "https://10.142.32.198:7443"
    KUBE_YAML_SIG = "${TIME_STAMP}_${BUILD_NUMBER}"
}

tools {
    gradle "gradle3.5"
}

stages {

    stage('获取代码') {
        when {
            allOf{
                environment name:"MODE",value:"deploy"
            }
        }
        steps {
            echo "获取代码"
            git branch: "${CODE_BRANCH}", credentialsId: "${GITLAB_CRE}", url: "${GITLAB_URL}"
        }
    }

    stage('构建项目') {
        when {
            allOf{
                environment name:"MODE",value:"deploy"
            }
        }
        steps {
            echo "构建项目"
            sh 'gradle  -x test clean build'
            sh '/bin/cp -f build/libs/* /${DOCKER_SITE}/${JOB_NAME}'
            //从workspace目录拷贝打包后的程序文件到jenkins操作docker的工作目录
        }
    }

    stage('生成Docker Image推送至Docker Registry') {
        when {
            allOf{
                environment name:"MODE",value:"deploy"
            }
        }
        steps {
            script {
                echo "生成Docker Image推送至Docker Registry"
                docker.withRegistry("https://${DOCKER_REGISTRY}", "${DOCKER_REGISTRY_CRE}") {
                    def CUSTOM_IMAGE = docker.build('${DEPLOY_NS}/${JOB_NAME}:${DOCKER_IMAGE_TAG}','-f /${DOCKER_SITE}/${JOB_NAME}/Dockerfile /${DOCKER_SITE}/${JOB_NAME}')
                    CUSTOM_IMAGE.push()
                    }
                }
            }
        }

    stage ("发布至Kubernetes") {
        when {
            allOf{
                environment name:"MODE",value:"deploy"
            }
        }
        steps {
            script {
                echo "发布至Kubernetes"
                withKubeConfig([credentialsId: "${KUBE_CRE}",serverUrl: "${KUBE_APISERVER}"]) {
                    sh "deploy.sh ${DOCKER_IMAGE_FULL_NAME} ${DEPLOY_NS} ${JOB_NAME} ${KUBE_YAML_SIG} ${DOCKER_SITE}"
                    //deploy.sh参数声明:
                    //arg1:docker image名称+标签
                    //arg2:将要部署到Kubernetes中的名称空间namespace
                    //arg3:项目名称
                    //arg4:项目的yaml文件标识(时间戳+当前构建号)
                    //arg5:jenkins操作docker的工作目录
                    }
                }
            }
        }
    }
}