pipeline {
	parameters {
		choice choices: ['kting', 'trunk', 'backup'], description: '选择部署环境 ', name: 'deploy_env'
		choice choices: ['NewApp', 'trunk'], description: '选择分支', name: 'deploy_branch'
	}
	
	environment {
		project_name = "${params.deploy_branch}"
		project_type = "order"
		project_env = "${params.deploy_env}"
		credId = "4ed64b8b-17d5-4800-b20b-4e2873c95d3b"
		gitlab_url = "http://gitlab.kting.cn/alex/HUAWEI_MUSIC_ORDER.git"
		scripts_dir = "/data/server/jenkins/scripts_build"
	}
	
	agent { label "${params.deploy_env}" }
	
    tools {
        gradle "gradle3.5"
    }
	
    stages {
	
		stage('清空目录') {
            steps {
                echo "清空目录"
				deleteDir()
            }
        }

        stage('获取代码') {
            steps {
                echo "获取代码"
				git branch: "${project_name}", credentialsId: "${credId}", url: "${gitlab_url}"
            }
        }

        stage('构建项目') {
            steps {
				echo "构建项目"
				sh 'gradle clean build'
            }
        }
		
        stage('部署检查') {
			parallel {
				stage('分发部署') {
					steps {
					sh '${scripts_dir}/salt_deploy.sh ${project_type} ${project_env}'
					}
				}
				stage('检查日志') {
					steps {
					sh '${scripts_dir}/checklog.sh ${project_type} ${project_env}'
					}
				}
			}
		}
	}
}